version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: whistledrop_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345678!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
